[services]
lutris = True
gog = True
egs = True
origin = True
ubisoft = True
steam = True

[lutris]
library_ignores = 
migration_version = 11
width = 1059
height = 607
window_x = 1051
window_y = 108
maximized = False
selected_category = category:all
show_advanced_options = False

