#! /bin/sh

## BSPWM configs
pgrep -x sxhkd > /dev/null || sxhkd &
bspc monitor -d I II III IV V VI VII VIII IX X
bspc config border_width         3
bspc config window_gap           8
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

## Border Color
bspc config normal_border_color "#1e1e2e"
bspc config focused_border_color "#eba0ac"
bspc config urgent_border_color "#B58900"
bspc config presel_border_color "#26E2FF"

## Rules
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Pavucontrol state=floating
bspc rule -a Easy Effects state=floating
bspc rule -a Protonvpn state=floating
bspc rule -a Lutris state=floating 
bspc rule -a Thorium-browser desktop='^2' follow=on focus=on
bspc rule -a discord desktop='^3' follow=on focus=on
bspc rule -a vibrantLinux desktop='^1' follow=no state=floating
bspc rule -a android-studio state=floating border=off follow=on
bspc rule -a Connman-gtk state=floating border=off
bspc rule -a steam desktop='^4' state=floating 
bspc rule -a heroic desktop='^4' state=floating

## Env Variables
export EDITOR=nvim
export VISUAL=nvim
export BROWSER=Thorium-browser
export TERMCMD=kitty







#AutoStart Functions
function run_applets() {
  applets=(picom flameshot nm-applet)

  for applet in "${applets[@]}"
  do
    $applet &
  done
}
run_applets


## Env Variables needed for java applications to work properly
wmname LG3D &
export _JAVA_AWT_WM_NONREPARENTING=1

## zzz
xrdb ${HOME}/.Xresources
$HOME/.config/polybar/launch.sh &
$HOME/.fehbg
vibrant-cli DVI-D-0 1.25 &

#Refresh Rate
$HOME/70hz.sh &

# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

